# configfile: "config.yaml"

rule reverse_geocode_address:
    input:
        "data/interim/combined_data_without_gaps.csv"
    output:
        "data/external/reverse_geocoded_data.json"
    shell:
        "python -m src.data.reverse_geocode_address {input} {output}"

rule gaps_filling:
    input:
        "data/interim/combined_data.csv",
        "data/external/geocoded_data.csv"
    output:
        "data/interim/combined_data_without_gaps.csv",
        "data/interim/manual_check_data.csv"
    shell:
        "python -m src.data.gaps_filling {input} {output}"

rule gaps_geocoding:
    input:
        "data/interim/find_gaps.csv"
    output:
        "data/external/geocoded_data.csv"
    shell:
        "python -m src.data.gaps_geocoding {input} {output}"

rule find_gaps:
    input:
        "data/interim/combined_data.csv"
    output:
        "data/interim/find_gaps.csv"
    shell:
        "python -m src.data.find_gaps {input} {output}"

rule combine_data:
    input:
        "data/raw/train.csv",
        "data/raw/test.csv"
    output:
        "data/interim/combined_data.csv"
    shell:
        "python -m src.data.combine_data {input} {output}"