# configfile: "config.yaml"

rule get_osm_data:
    # comment output for activate download and update OSM data
    output:
        "data/external/russia-latest.osm.pbf"
    conda:
        "ox"
    shell:
        "python -m src.data.get_osm_data russia data/external"

rule add_city:
    input:
        ["data/interim/cleaned_data_v2.csv", "data/external/geocoded_addresses.json"]
    output:
        "data/interim/cleaned_data_with_city.csv"
    shell:
        "python -m src.features.add_city {input} {output}"

rule clean_address:
    input:
        ["data/interim/combined_data_v2.csv", "data/external/geocoded_addresses.json"]
    output:
        ["data/interim/cleaned_data_v2.csv", "data/interim/manual_address_check_v2.csv"]
    shell:
        "python -m src.data.clean_address {input} {output} 1"

rule geocode_address:
    input:
        "data/interim/combined_data_v2.csv"
    output:
        "data/external/geocoded_addresses.json"
    shell:
        "python -m src.data.geocode_address {input} {output}"

rule combine_data:
    input:
        "data/raw/train.csv",
        "data/raw/test.csv"
    output:
        "data/interim/combined_data_v2.csv"
    shell:
        "python -m src.data.combine_data {input} {output}"