name: Lint test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: flake8 lint
        uses: py-actions/flake8@v2
        with:
          path: "src"
          max-line-length: "88"
      - name: Test with mypy
        run: mypy src/data --ignore-missing-imports
