name: Lint test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          python --version
          python -m venv ./venv
          Invoke-Expression ( "venv/Scripts/activate.ps1" )
          pip install flake8 mypy
      - name: Lint with flake8
        run: flake8 src/data
      - name: Test with mypy
        run: mypy src/data --ignore-missing-imports