name: Lint test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          pip install flake8 mypy
      - name: Lint with flake8
        run: flake8 src/data
      - name: Test with mypy
        run: mypy src/data --ignore-missing-imports